# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7482f08e31b63e261e40d1826ab098a3"
name = "product-discount-nd"
handle = "product-discount-nd"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "orderdiscount.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
